force-app/main/default/objects/CIHI__c/CIHI__c.object-meta.xml
<CustomObject>
    <label>CIHI</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>CIHI ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CIHI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CIHI__c/fields/Basic_Education_Institution_Code__c.field-meta.xml
<CustomField>
    <fullName>Basic_Education_Institution_Code__c</fullName>
    <formula>CA_Uni_of_Grad_for_Basic_Edu_in_Pharmacy__r.CIHI_Code__c</formula>
    <label>Basic Education Institution Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Concurrent_Reg_Province_Territory__c.field-meta.xml
<CustomField>
    <fullName>Concurrent_Reg_Province_Territory__c</fullName>
    <inlineHelpText>Any other Canadian province or territory that a provider is licensed in (for the same profession) at the time of renewal. Each provider may select up to 3 provinces/territories.</inlineHelpText>
    <label>Concurrent Reg Province/Territory</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CIHI_Province_State_Value_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Concurrent_Registration_Country__c.field-meta.xml
<CustomField>
    <fullName>Concurrent_Registration_Country__c</fullName>
    <inlineHelpText>Any other country that a provider is licensed in (for the same profession) at the time of renewal. Each provider may select up to 3 countries.</inlineHelpText>
    <label>Concurrent Registration Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CIHI_Country_Value_Set</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Date_of_Initial_Registration__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Initial_Registration__c</fullName>
    <label>Initial Licensure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Highest_Education_Institution_Code__c.field-meta.xml
<CustomField>
    <fullName>Highest_Education_Institution_Code__c</fullName>
    <formula>CA_University_of_Grad_Highest_Level__r.CIHI_Code__c</formula>
    <label>Highest Education Institution Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Postal_Code_of_Primary_Employment__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code_of_Primary_Employment__c</fullName>
    <label>Postal Code of Primary Employment</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Postal_Code_of_Residence__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code_of_Residence__c</fullName>
    <label>Postal Code of Residence</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Postal_Code_of_Secondary_Employment__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code_of_Secondary_Employment__c</fullName>
    <label>Postal Code of Secondary Employment</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Postal_Code_of_Third_Employment__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code_of_Third_Employment__c</fullName>
    <label>Postal Code of Third Employment</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Primary_Employer_Organization_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Primary_Employer_Organization_Identifier__c</fullName>
    <label>Primary Employer Organization Identifier</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Primary_Employment_Annual_Earned_Hours__c.field-meta.xml
<CustomField>
    <fullName>Primary_Employment_Annual_Earned_Hours__c</fullName>
    <label>Primary Employment Annual Earned Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Provider_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Provider_Registration_Number__c</fullName>
    <formula>IF(LEN(Registration__r.Name)&lt;16,LPAD(Registration__r.Name,16,&apos; &apos;),Registration__r.Name)</formula>
    <label>Provider Registration Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Racialized_Group_1__c.field-meta.xml
<CustomField>
    <fullName>Racialized_Group_1__c</fullName>
    <label>Racialized Group 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Racialized_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Racialized_Group_2__c.field-meta.xml
<CustomField>
    <fullName>Racialized_Group_2__c</fullName>
    <label>Racialized Group 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Racialized_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Racialized_Group_3__c.field-meta.xml
<CustomField>
    <fullName>Racialized_Group_3__c</fullName>
    <label>Racialized Group 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Racialized_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <formula>IF(ISPICKVAL(Registration__r.Registration_Status__c, &apos;Active&apos;),
IF( ISPICKVAL( Registration__r.Class__c , &apos;Practicing Direct&apos;),&apos;Active, full&apos;,&apos;Active, other&apos;),
TEXT(Registration__r.Registration_Status__c))</formula>
    <label>Registration Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Secondary_Employer_Organization_Identifi__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Employer_Organization_Identifi__c</fullName>
    <label>Secondary Employer Organization Identifi</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Secondary_Employment_Annual_Earned_Hours__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Employment_Annual_Earned_Hours__c</fullName>
    <label>Secondary Employment Annual Earned Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Tertiary_Employer_Organization_Identifie__c.field-meta.xml
<CustomField>
    <fullName>Tertiary_Employer_Organization_Identifie__c</fullName>
    <label>Tertiary Employer Organization Identifie</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Third_Employment_Annual_Earned_Hours__c.field-meta.xml
<CustomField>
    <fullName>Third_Employment_Annual_Earned_Hours__c</fullName>
    <label>Third Employment Annual Earned Hours</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Year_of_Grad_Basic_Education_in_Pharmacy__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Grad_Basic_Education_in_Pharmacy__c</fullName>
    <label>Basic Pharmacy Education Graduation Yr.</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Year_of_Grad_Highest_of_Post_Basic_Edu__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Grad_Highest_of_Post_Basic_Edu__c</fullName>
    <label>Highest Level of Pharmacy Education Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CIHI__c/fields/Year_of_Initial_Registration__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Initial_Registration__c</fullName>
    <formula>TEXT(YEAR( Date_of_Initial_Registration__c ) )</formula>
    <label>Year of Initial Registration</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIHI_and_Salesforce_Field__mdt/CIHI_and_Salesforce_Field__mdt.object-meta.xml
<CustomObject>
    <label>CIHI and Salesforce Field</label>
    <pluralLabel>CIHI and Salesforce Fields</pluralLabel>
</CustomObject>

force-app/main/default/objects/CIHI_and_Salesforce_Field__mdt/fields/Main_CIHI_Field__c.field-meta.xml
<CustomField>
    <fullName>Main_CIHI_Field__c</fullName>
    <label>Main CIHI Field</label>
    <referenceTo>Main_CIHI_Fields__mdt</referenceTo>
    <relationshipLabel>CIHI and Salesforce Fields</relationshipLabel>
    <relationshipName>CIHI_and_Salesforce_Fields</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/CIHI_Code_and_Value__mdt/CIHI_Code_and_Value__mdt.object-meta.xml
<CustomObject>
    <label>CIHI Code and Value</label>
    <pluralLabel>CIHI Code and Values</pluralLabel>
</CustomObject>

force-app/main/default/objects/CIHI_Code_and_Value__mdt/fields/CIHI_Code__c.field-meta.xml
<CustomField>
    <fullName>CIHI_Code__c</fullName>
    <label>CIHI Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIHI_Code_and_Value__mdt/fields/CIHI_Value__c.field-meta.xml
<CustomField>
    <fullName>CIHI_Value__c</fullName>
    <label>CIHI Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIHI_Code_and_Value__mdt/fields/Main_CIHI_Field__c.field-meta.xml
<CustomField>
    <fullName>Main_CIHI_Field__c</fullName>
    <label>Main CIHI Field</label>
    <referenceTo>Main_CIHI_Fields__mdt</referenceTo>
    <relationshipLabel>CIHI Code and Values</relationshipLabel>
    <relationshipName>CIHI_Code_and_Values</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Main_CIHI_Fields__mdt/Main_CIHI_Fields__mdt.object-meta.xml
<CustomObject>
    <label>Main CIHI Field</label>
    <pluralLabel>Main CIHI Fields</pluralLabel>
</CustomObject>

force-app/main/default/globalValueSets/CIHI_Country_Value_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Not Collected</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Åland Islands</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <masterLabel>CIHI Country Value Set</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/CIHI_Province_State_Value_Set.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Newfoundland and Labrador</fullName>
    </customValue>
    <customValue>
        <fullName>Prince Edward Island</fullName>
    </customValue>
    <customValue>
        <fullName>Nova Scotia</fullName>
    </customValue>
    <customValue>
        <fullName>New Brunswick</fullName>
    </customValue>
    <customValue>
        <fullName>Quebec</fullName>
    </customValue>
    <customValue>
        <fullName>Ontario</fullName>
    </customValue>
    <customValue>
        <fullName>Manitoba</fullName>
    </customValue>
    <customValue>
        <fullName>Saskatchewan</fullName>
    </customValue>
    <customValue>
        <fullName>Alberta</fullName>
    </customValue>
    <customValue>
        <fullName>British Columbia</fullName>
    </customValue>
    <customValue>
        <fullName>Yukon</fullName>
    </customValue>
    <customValue>
        <fullName>Northwest Territories</fullName>
    </customValue>
    <customValue>
        <fullName>Nunavut</fullName>
    </customValue>
    <customValue>
        <fullName>Not collected</fullName>
    </customValue>
    <customValue>
        <fullName>Not applicable</fullName>
    </customValue>
    <customValue>
        <fullName>Unknown</fullName>
    </customValue>
    <masterLabel>CIHI Province/State Value Set</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Racialized_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>Black</label>
    </customValue>
    <customValue>
        <fullName>15</fullName>
        <label>East Asian</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Indigenous</label>
    </customValue>
    <customValue>
        <fullName>25</fullName>
        <label>Latin American</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>Middle Eastern</label>
    </customValue>
    <customValue>
        <fullName>35</fullName>
        <label>South Asian</label>
    </customValue>
    <customValue>
        <fullName>40</fullName>
        <label>Southeast Asian</label>
    </customValue>
    <customValue>
        <fullName>45</fullName>
        <label>White</label>
    </customValue>
    <customValue>
        <fullName>50</fullName>
        <label>Mixed Racial Group</label>
    </customValue>
    <customValue>
        <fullName>59</fullName>
        <label>Another Race Category</label>
    </customValue>
    <customValue>
        <fullName>95</fullName>
        <label>Do not know</label>
    </customValue>
    <customValue>
        <fullName>96</fullName>
        <label>Prefer not to answer</label>
    </customValue>
    <masterLabel>Racialized Group</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/generateCIHIReportController.cls
public with sharing class generateCIHIReportController {
    static final String NOT_COLLECTED = 'Not applicable';
    static final string PROVIDER_TYPE = '206';
    static final string NATIONAL_UNIQUE_IDENTIFIER = '9999999999999999999999999999999999999999999999999999999999999998';
    @AuraEnabled(cacheable=false)
    public static List<String> generateCIHIReport(String renewalYear) {
        // Define the object and field set API names
        String cihiRow = '';
        List<String> cihiOutput = new List<String>();
        String objectAPIName = 'CIHI__c';
        String fieldSetName = 'CIHI_Fields';
        String sfAndCIHI_mdt = 'CIHI_and_Salesforce_Field__mdt';
        String CIHI_Master = 'Main_CIHI_Fields__mdt';
        String CIHI_Codes = 'CIHI_Code_and_Value__mdt';
        List<String> fieldList  = new List<String>();
        DateTime currentDt = Datetime.now();
        Map<String,Map<String,String>> CIHiFieldAndValueCodeMap = new Map<String,Map<String,String>>();

        // Get the field set information
        Schema.SObjectType objectType = Schema.getGlobalDescribe().get(objectAPIName);
        Schema.DescribeSObjectResult objectDescribe = objectType.getDescribe();
        Schema.FieldSet fieldSet = objectDescribe.fieldSets.getMap().get(fieldSetName);

        // Retrieve the field set fields
        List<Schema.FieldSetMember> fieldSetMembers = fieldSet.getFields();

        // Create a dynamic query to fetch the fields specified in the field set
        String query = 'SELECT Date_of_Initial_Registration__c,Registration_Status__c,Provider_Registration_Number__c,';
        for (Schema.FieldSetMember fieldSetMember : fieldSetMembers) {
            query += fieldSetMember.getFieldPath() + ', ';
            fieldList.add(fieldSetMember.getFieldPath());
        }
        query = query.removeEnd(', ') + ' FROM ' + objectAPIName+' where Renewal_Year__c=:renewalYear';
        List<CIHI_Code_and_Value__mdt> CIHI_CodeMap = CIHI_Code_and_Value__mdt.getAll().values();
        for(CIHI_Code_and_Value__mdt cvmdt : CIHI_CodeMap){
            if(CIHiFieldAndValueCodeMap.get(cvmdt.Main_CIHI_Field__c) == null){
                CIHiFieldAndValueCodeMap.put(cvmdt.Main_CIHI_Field__c, new Map<String,String>{cvmdt.CIHI_Value__c=>cvmdt.CIHI_Code__c});
            }else{
                CIHiFieldAndValueCodeMap.get(cvmdt.Main_CIHI_Field__c).put(cvmdt.CIHI_Value__c,cvmdt.CIHI_Code__c);
            }
        }
        // Execute the query
        List<CIHI__c> records = Database.query(query);
        cihiOutput.add(getControlRow(renewalYear,records,currentDt));
        for(CIHI__c rec: records){
            Date d = rec.Date_of_Initial_Registration__c;
            cihiRow+=PROVIDER_TYPE+rec.Registration_Status__c+DateTime.newInstance(d.year(), d.month(), d.day()).format('yyyyMM')+NATIONAL_UNIQUE_IDENTIFIER+' '.repeat(16-rec.Provider_Registration_Number__c.length())+rec.Provider_Registration_Number__c;
            for(String fieldName : fieldList){
                System.debug(fieldName);
                try{
                    CIHI_and_Salesforce_Field__mdt csf = CIHI_and_Salesforce_Field__mdt.getInstance(removePostfix(fieldName));
                    if(rec.get(fieldName)==null){
                        cihiRow +=CIHiFieldAndValueCodeMap.get(csf.Main_CIHI_Field__c).get(NOT_COLLECTED);
                    }else{
                        switch on fieldName {
                            when 'Primary_Employer_Organization_Identifier__c','Secondary_Employer_Organization_Identifi__c','Tertiary_Employer_Organization_Identifie__c'{
                                cihiRow+='9999999998';
                            }
                            when  'Concurrent_Reg_Province_Territory__c'{
                                Integer count = 0;
                                for(String str : getFieldValue(rec,fieldName).split(';')){
                                    cihiRow += fetchDataFromMD(CIHiFieldAndValueCodeMap,csf.Main_CIHI_Field__c,str);
                                    count+=1;
                                    if(count==3){
                                        break;
                                    }
                                }
                                if(count<3){
                                    cihiRow+='98'.repeat(3-count);
                                }          
                            }
                            when  'Concurrent_Registration_Country__c'{
                                Integer count = 0;
                                for(String str : getFieldValue(rec,fieldName).split(';')){
                                    cihiRow += fetchDataFromMD(CIHiFieldAndValueCodeMap,csf.Main_CIHI_Field__c,str);
                                    count+=1;
                                    if(count==3){
                                        break;
                                    }
                                }
                                if(count<3){
                                    cihiRow+='998'.repeat(3-count);
                                }          
                            }
                            when 'Year_of_Initial_Registration__c'{
                                cihiRow+=rec.get(fieldName);
                            }
                            when 'Year_of_Birth__c'{
                                cihiRow+=rec.get(fieldName);
                            }
                            when 'Racialized_Group_1__c','Racialized_Group_2__c','Racialized_Group_3__c'{
                                cihiRow+=rec.get(fieldName);
                            }
                            when 'Postal_Code_of_Residence__c','Postal_Code_of_Primary_Employment__c','Postal_Code_of_Secondary_Employment__c','Postal_Code_of_Third_Employment__c'{
                                String tempStr = (String)rec.get(fieldName);
                                tempStr=tempStr.replace(' ','');
                                tempStr = tempStr.replace('-','');
                                if(tempStr.length()!=6){
                                    cihiRow+='999998';
                                }else{
                                    cihiRow+=tempStr.toUpperCase();
                                }
                            }
                            when 'Year_of_Grad_Highest_of_Post_Basic_Edu__c'{
                                cihiRow+=rec.get(fieldName);
                            }
                            when 'Year_of_Grad_Basic_Education_in_Pharmacy__c'{
                                cihiRow+=rec.get(fieldName);
                            }
                            when 'Basic_Education_Institution_Code__c','Highest_Education_Institution_Code__c'{
                                cihiRow+=rec.get(fieldName);
                            }
                            when 'Primary_Employment_Annual_Earned_Hours__c','Secondary_Employment_Annual_Earned_Hours__c','Third_Employment_Annual_Earned_Hours__c'{
                                cihiRow+=' '.repeat(4-calHours(rec,fieldName).length())+calHours(rec,fieldName);
                            }
                            when else {
                                cihiRow += fetchDataFromMD(CIHiFieldAndValueCodeMap,csf.Main_CIHI_Field__c,getFieldValue(rec,fieldName));
                            }
                        }
                    }
                }catch(Exception e){
                    System.debug('Error--'+e.getMessage()+' : '+fieldName);
                }
                System.debug(cihiRow);
            }
            cihiOutput.add(cihiRow);
            cihiRow = '';
        }
        return cihiOutput;
    }

    public static String removePostfix(String fieldName){
        return fieldName.removeEnd('__c');
    }

    public static String getFieldValue(CIHI__c rec, String fieldName){
        return String.valueOf(rec.get(fieldName));
    }
    public static String calHours(CIHI__c rec, String fieldName){
        Decimal d = (Decimal)rec.get(fieldName);
        return String.valueOf(d.intValue()).right(4);
    }
    public static String getControlRow(String renewalYear,List<CIHI__c> records,DateTime currentDt){
        Integer length = String.valueOf(records.size()).length();
        String nOfRecords = '0'.repeat(6-length)+String.valueOf(records.size());
        return 'PHANS001'+renewalYear+nOfRecords+currentDt.format('yyyyMMdd')+'R'+'X'.repeat(363);
    }
    public static String fetchDataFromMD(Map<String,Map<String,String>> CIHiFieldAndValueCodeMap,String CIHIField,String Value){
        if(CIHiFieldAndValueCodeMap.get(CIHIField)!=null){
            if(CIHiFieldAndValueCodeMap.get(CIHIField).get(Value)!=null){
                return CIHiFieldAndValueCodeMap.get(CIHIField).get(Value);
            }else{
                return NOT_COLLECTED;
            } 
        }else{
            return null;
        }
    }
}