force-app/main/default/objects/Case/fields/Pending_Status__c.field-meta.xml
<CustomField>
    <fullName>Pending_Status__c</fullName>
    <label>Pending Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registrant</fullName>
            </value>
            <value>
                <fullName>NSCP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Application_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Status__c.field-meta.xml
<CustomField>
    <fullName>Document_Status__c</fullName>
    <label>Document Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/terrabbit_uploadDocumentControllerTest.cls
@isTest()
private class terrabbit_uploadDocumentControllerTest {
    @testSetup static void setup() {
        List<ContentVersion> lcv = new List<ContentVersion>();
        List<ContentDocumentLink> lcdl = new List<ContentDocumentLink>();

        Case c01 = new Case(Status='New',Pending_Status__c='NSCP');
        Case c02 = new Case(Status='New',Pending_Status__c='Registrant');
        insert new List<Case>{c01,c02};
        Document__c d01 = new Document__c(Name='Test Document 01',Description__c='Test Description',Document_Status__c= 'Submitted',Application__c=c01.id);
        Document__c d02 = new Document__c(Name='Test Document 02',Description__c='Test Description',Document_Status__c= 'New',Application__c=c02.id);
        insert new List<Document__c>{d01,d02};
        
        ContentVersion contentVersion1 = new ContentVersion(
            Title          = 'Test Document 01',
            PathOnClient   = 'Pic01.jpg',
            VersionData    = Blob.valueOf('Test Content 01'),
            IsMajorVersion = true);
            lcv.add(contentVersion1);
        ContentVersion contentVersion2 = new ContentVersion(
            Title          = 'Test Document 02',
            PathOnClient   = 'Pic02.jpg',
            VersionData    = Blob.valueOf('Test Content 02'),
            IsMajorVersion = true);
            lcv.add(contentVersion2);
        insert lcv;
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        ContentDocumentLink cdl01 = new ContentDocumentLink();
            cdl01.LinkedEntityId = d01.id;
            cdl01.ContentDocumentId = documents[0].Id;
            cdl01.ShareType = 'V';
            cdl01.Visibility = 'AllUsers';
            lcdl.add(cdl01);
            ContentDocumentLink cdl02 = new ContentDocumentLink();
            cdl02.LinkedEntityId = d02.id;
            cdl02.ContentDocumentId = documents[1].Id;
            cdl02.ShareType = 'V';
            cdl02.Visibility = 'AllUsers';
            lcdl.add(cdl02);
        insert lcdl;
        }

    @isTest
    static void myUnitTest() {
        // TO DO: implement unit test
        List<Case> c = [Select id from case];
        terrabbit_uploadDocumentController.getApplicationTemplate(c.get(0).id);
        terrabbit_uploadDocumentController.getApplicationTemplate(c.get(1).id);
    }
}