force-app/main/default/objects/Account/recordTypes/Pharmacy.recordType-meta.xml
<RecordType>
    <fullName>Pharmacy</fullName>
    <active>true</active>
    <label>Pharmacy</label>
</RecordType>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Authorized_To_Administer_By_Injection__c.field-meta.xml
<CustomField>
    <fullName>Authorized_To_Administer_By_Injection__c</fullName>
    <label>Authorized To Administer By Injection</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Conditions_on_Licence__c.field-meta.xml
<CustomField>
    <fullName>Conditions_on_Licence__c</fullName>
    <label>Conditions on Licence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/NSCP_Registration_Number1__c.field-meta.xml
<CustomField>
    <fullName>NSCP_Registration_Number1__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <label>Pharmacy License Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registrant__c.field-meta.xml
<CustomField>
    <fullName>Registrant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registrant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Account_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/recordTypes/Pharmacy.recordType-meta.xml
<RecordType>
    <fullName>Pharmacy</fullName>
    <active>true</active>
    <label>Pharmacy</label>
</RecordType>

force-app/main/default/objects/Registration__c/recordTypes/Practitioner.recordType-meta.xml
<RecordType>
    <fullName>Practitioner</fullName>
    <active>true</active>
    <label>Practitioner</label>
</RecordType>

force-app/main/default/globalValueSets/Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Practicing Direct</fullName>
        <label>Practicing Direct Patient Care</label>
    </customValue>
    <customValue>
        <fullName>Practicing Indirect</fullName>
        <label>Practicing Indirect Patient Care</label>
    </customValue>
    <customValue>
        <fullName>Non-Practicing</fullName>
        <label>Non-Practicing Patient Care</label>
    </customValue>
    <masterLabel>Class</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/publicSearchDataService.cls
public with sharing class publicSearchDataService {

    @AuraEnabled(cacheable=true)
    public static List<Registration__c> getPharmacyRecords(Boolean filter,String licenseNumber,String Address,String City,String Street){
        Id rcdTypeId = publicSearchDataService.getRecordTypeId('Pharmacy');
        String licenseNumb = String.isNotBlank(licenseNumber)?licenseNumber:null;
        String regStatus = 'Active';
        String queryStr = 'Select id,Expiry_Date__c,Registrant__r.Name,Registrant__r.BillingAddress, Registrant__r.Phone, Registrant__r.Fax,NSCP_Registration_Number1__c from Registration__c where RecordTypeId =:rcdTypeId and Registration_Status__c =: regStatus';
        String searchTerm = String.isNotBlank(Address)?'%'+Address+'%':null;
        String searchCity = String.isNotBlank(City)?'%'+City+'%':null;
        String searchStreet = String.isNotBlank(Street)?'%'+Street+'%':null;
        String tempQuery = '';
        if(filter){
            return Database.query(queryStr);
        }else{
            if(licenseNumb!=null && (String.isNotBlank(Address) || String.isNotBlank(City) || String.isNotBlank(Street))){
                tempQuery='NSCP_Registration_Number1__c =:licenseNumb or (Registrant__r.BillingCountry like :searchTerm or Registrant__r.BillingCity like :searchCity or Registrant__r.BillingStreet like :searchStreet)';
            }else if(licenseNumb!=null){
                tempQuery='NSCP_Registration_Number1__c =:licenseNumb';
            }else if(String.isNotBlank(Address) && String.isNotBlank(City) && String.isNotBlank(Street)){
                tempQuery='Registrant__r.BillingCountry like :searchTerm or Registrant__r.BillingCity like :searchCity or Registrant__r.BillingStreet like :searchStreet';
            }else if(String.isNotBlank(Address) && String.isNotBlank(City)){
                tempQuery='Registrant__r.BillingCountry like :searchTerm or Registrant__r.BillingCity like :searchCity';
            }else if(String.isNotBlank(City) && String.isNotBlank(Street)){
                tempQuery='Registrant__r.BillingCity like :searchCity or Registrant__r.BillingStreet like :searchStreet';
            }else if(String.isNotBlank(Address) && String.isNotBlank(Street)){
                tempQuery='Registrant__r.BillingCountry like :searchTerm or Registrant__r.BillingStreet like :searchStreet';
            }else if(String.isNotBlank(Address)){
                tempQuery='Registrant__r.BillingCountry like :searchTerm';
            }else if(String.isNotBlank(City)){
                tempQuery='Registrant__r.BillingCity like :searchCity';
            }else if(String.isNotBlank(Street)){
               tempQuery='Registrant__r.BillingStreet like :searchStreet';
            }else{
                return new List<Registration__c>();
            }
            System.debug(queryStr + ' and ' +tempQuery);
            return Database.query(queryStr + ' and ' +'('+tempQuery+')');
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<Registration__c> getPharmacistRecords(Boolean filter,String licenseNumber,String firstName,String lastName){
        Id rcdTypeId = publicSearchDataService.getRecordTypeId('Practitioner');
        Set<String> types = new Set<String>{'Pharmacist','Pharmacy Technician'};
        String regStatus = 'Active';
        String regClass = 'Non-Practicing';
        String queryStr = 'Select id,Name,Type__c,Registration_Status__c,toLabel(Class__c),Expiry_Date__c,Registrant__r.FirstName,Registrant__r.LastName,Conditions_on_Licence__c,Authorized_To_Administer_By_Injection__c from Registration__c where RecordTypeId=:rcdTypeId and Type__c in:types and Registration_Status__c =:regStatus and Class__c!=:regClass and Expiry_Date__c >= TODAY';
        String searchTermFN = '%'+firstName+'%';
        String searchTermLN = '%'+lastName+'%';
        String licenseNumb = String.isNotBlank(licenseNumber)?licenseNumber:null;
        String tempQuery = '';
        if(filter){
            return Database.query(queryStr+' order by Registrant__r.LastName');
        }else if(licenseNumb!=null && (String.isNotBlank(firstName) || String.isNotBlank(lastName))){
            System.debug('all good');
            tempQuery=' Name =:licenseNumb or Registrant__r.FirstName like :searchTermFN or Registrant__r.LastName like :searchTermLN';
        }else if(licenseNumb != null){
            System.debug('license good');
            tempQuery=' Name =:licenseNumb';
        }else if(String.isNotBlank(firstName) || String.isNotBlank(lastName)){
            System.debug('first name or last name good');
            if(String.isNotBlank(firstName) && String.isNotBlank(lastName)){
                tempQuery=' Registrant__r.FirstName like :searchTermFN or Registrant__r.LastName like :searchTermLN';
            }else if(String.isNotBlank(firstName)){
                tempQuery=' Registrant__r.FirstName like :searchTermFN';
            }else if(String.isNotBlank(lastName)){
                tempQuery=' Registrant__r.LastName like :searchTermLN';
            }
        }else{
            return new List<Registration__c>();
        }
        return Database.query(queryStr+' and ' +'('+tempQuery+')'+' order by Registrant__r.LastName ASC');
    }

    public static id getRecordTypeId(String recordTypeName){
        return Schema.Sobjecttype.Registration__c.getRecordTypeInfosByDeveloperName().get(recordTypeName).getRecordTypeId();
    }
}