force-app/main/default/objects/Account/fields/Pharmacy_Manager__c.field-meta.xml
<CustomField>
    <fullName>Pharmacy_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pharmacy Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Managed Pharmacies</relationshipLabel>
    <relationshipName>Pharmacy_Manager_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Conditions_on_Licence__c.field-meta.xml
<CustomField>
    <fullName>Conditions_on_Licence__c</fullName>
    <label>Conditions on Licence</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Authorized_To_Administer_By_Injection__c.field-meta.xml
<CustomField>
    <fullName>Authorized_To_Administer_By_Injection__c</fullName>
    <label>Authorized To Administer By Injection</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Conditions_on_Licence__c.field-meta.xml
<CustomField>
    <fullName>Conditions_on_Licence__c</fullName>
    <label>Conditions on Licence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Convocation__c.field-meta.xml
<CustomField>
    <fullName>Convocation__c</fullName>
    <description>graduating institution i.e Niagara College</description>
    <label>Convocation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Initial_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Initial_Registration_Date__c</fullName>
    <inlineHelpText>The first time that a registrant Licensed in any jurisdiction</inlineHelpText>
    <label>Initial Licensure Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/NSCP_Registration_Number1__c.field-meta.xml
<CustomField>
    <fullName>NSCP_Registration_Number1__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <label>Pharmacy License Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Pharmacy_Manager__c.field-meta.xml
<CustomField>
    <fullName>Pharmacy_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pharmacy Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Registrations (Pharmacy Manager)</relationshipLabel>
    <relationshipName>Registrations2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Pharmacy_Owner_Account__c.field-meta.xml
<CustomField>
    <fullName>Pharmacy_Owner_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pharmacy Owner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registrations (Pharmacy Owner)</relationshipLabel>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registrant__c.field-meta.xml
<CustomField>
    <fullName>Registrant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registrant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Account_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Valid_from_Date__c.field-meta.xml
<CustomField>
    <fullName>Valid_from_Date__c</fullName>
    <label>Valid from Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Practicing Direct</fullName>
        <label>Practicing Direct Patient Care</label>
    </customValue>
    <customValue>
        <fullName>Practicing Indirect</fullName>
        <label>Practicing Indirect Patient Care</label>
    </customValue>
    <customValue>
        <fullName>Non-Practicing</fullName>
        <label>Non-Practicing Patient Care</label>
    </customValue>
    <masterLabel>Class</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PdfGenerator.cls
public with sharing class PdfGenerator {
	@AuraEnabled
	public static Registration__c getCertPharmacistLicenseController(String currentRecordId){
		return [SELECT Id, Name, Registrant__r.Name from Registration__c where id = :currentRecordId];
	}

	@AuraEnabled
	public static Registration__c getCertPharmacyTechLicenseController(String currentRecordId){
		return [SELECT Id, Name, Registrant__r.Name from Registration__c where id = :currentRecordId];
	}
	
	@AuraEnabled
	public static Registration__c getCertPharmacyLicenseController(String currentRecordId){
		return [SELECT Id, NSCP_Registration_Number1__c, Registrant__r.Name, Pharmacy_Owner_Account__r.Name, Registrant__r.Pharmacy_Manager__r.FirstName, Registrant__r.Pharmacy_Manager__r.LastName, Registrant__r.BillingStreet,  Registrant__r.BillingCity, Registrant__r.BillingState from Registration__c where id = :currentRecordId];
	}
	
	@AuraEnabled
	public static Registration__c getLetterOfStandingPharmTechController(String currentRecordId){
		return [SELECT Id, Convocation__c, Graduation_Date__c, Name, Registrant__r.Name, Registrant__r.PersonBirthdate, Registrant__r.PersonMailingAddress, Initial_Registration_Date__c, Type__c, toLabel(Class__c), Conditions_on_Licence__c, Authorized_To_Administer_By_Injection__c, Valid_from_Date__c, Expiry_Date__c from Registration__c where id = :currentRecordId];
	}
	
}