force-app/main/default/objects/Account/fields/Pharmacy_Licence_Number__c.field-meta.xml
<CustomField>
    <fullName>Pharmacy_Licence_Number__c</fullName>
    <label>Pharmacy Licence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Class</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Registrant__c.field-meta.xml
<CustomField>
    <fullName>Registrant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Registrant</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registrations</relationshipLabel>
    <relationshipName>Account_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Practicing Direct</fullName>
        <label>Practicing Direct Patient Care</label>
    </customValue>
    <customValue>
        <fullName>Practicing Indirect</fullName>
        <label>Practicing Indirect Patient Care</label>
    </customValue>
    <customValue>
        <fullName>Non-Practicing</fullName>
        <label>Non-Practicing Patient Care</label>
    </customValue>
    <masterLabel>Class</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/publicSearchDataServiceTest.cls
@isTest
private class publicSearchDataServiceTest {
    @TestSetup static void createRegister() {
        
        Account acc = new Account(FirstName = 'TestAcctFirstName',
                                      LastName='TestAcctLastName',
                                      Pharmacy_Licence_Number__c= 2012,
                                      PersonMailingCity='Montreal',
                                      PersonMailingCountry= 'Canada');
        insert acc; 
        List<Registration__c> testReg = new List<Registration__c>();
        for(Integer i=0;i<2;i++) {
            testReg.add(new Registration__c(Type__c='Pharmacist',
                                            Class__c='Practicing Direct',
                                            Expiry_Date__c=Date.newInstance(2025, 12, 31),
                                            Registrant__c=acc.id));
        }
        insert testReg; 
    }
    @isTest
    static void getPharmacyRecordsTest() {
        // retrive all data
        List<Registration__c> data = new List<Registration__c>();
        data = publicSearchDataService.getPharmacyRecords(true,'0','','','');
        //retrive filter data
        data = publicSearchDataService.getPharmacyRecords(false,'2012','Canada','Montreal','Hi');
        data = publicSearchDataService.getPharmacyRecords(false,'2012',null,null,null);
        data = publicSearchDataService.getPharmacyRecords(false,null,null,null,null);
    }
     @isTest
    static void getPharmacyRecordsTest1() {
        // retrive all data
        List<Registration__c> data = new List<Registration__c>();
        data = publicSearchDataService.getPharmacyRecords(false,null,null,null,null);
    }
    @isTest
    static void getPharmacyRecordsTest2() {
        // retrive all data
        List<Registration__c> data = new List<Registration__c>();
         data = publicSearchDataService.getPharmacyRecords(false,null,'Canada','Montreal','Hi');
    }
    @isTest
    static void getPharmacistRecordsTest(){
        List<Registration__c> data = new List<Registration__c>();
        data = publicSearchDataService.getPharmacistRecords(true,null,null,null);
        // data = publicSearchDataService.getPharmacistRecords(false,'2012','TestAcctFirstName','TestAcctLastName');
        data = publicSearchDataService.getPharmacistRecords(false,'2012',null,null);
        data = publicSearchDataService.getPharmacistRecords(false,null,'TestAcctFirstName',null);
        data = publicSearchDataService.getPharmacistRecords(false,null,null,'TestAcctLastName');
        data = publicSearchDataService.getPharmacistRecords(false,null,null,null);
    }
    @isTest
    static void getPharmacistRecordsTest1(){
        List<Registration__c> data = new List<Registration__c>();
        data = publicSearchDataService.getPharmacistRecords(false,null,null,null);
    }
    @isTest
    static void getPharmacistRecordsTest2(){
        List<Registration__c> data = new List<Registration__c>();
         data = publicSearchDataService.getPharmacistRecords(false,null,'TestAcctFirstName',null);
    }
}