force-app/main/default/objects/Fee__c/Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>ChargentOrders__ChargentOrder__c</referenceTo>
    <relationshipLabel>Fees</relationshipLabel>
    <relationshipName>Payment_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Total_With_HST__c.field-meta.xml
<CustomField>
    <fullName>Total_With_HST__c</fullName>
    <label>Total (With HST)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ConditionalButtonController.cls
public class ConditionalButtonController {
    private final ChargentOrders__ChargentOrder__c record;
    public List<Fee__c> fees {get; set;}
    
    
    
    public ConditionalButtonController(ApexPages.StandardController stdController) {
        this.record = (ChargentOrders__ChargentOrder__c) stdController.getRecord();
        this.fees = [SELECT Id, Name, Amount__c, Total_With_HST__c from Fee__c where Payment__r.Id = :this.record.Id];
        
    }
    
    public Boolean getHasFee() {
        return !fees.isEmpty();
    }
    
    
    public PageReference buttonAction() {
        try {
          //  String baseUrl =  URL.getOrgDomainUrl().toExternalForm(); // Get correct base URL
            Site site = [select id , name From Site where Name='NSCP_Registrant_Portal'].get(0) ;
            Domainsite ds = [select id, Domain.Domain  From DomainSite Where SiteId =: site.id].get(0) ;
            String baseUrl = 'https://' + ds.Domain.Domain  ;//{!Get_Domain_Site_To_Build_URL.Domain.Domain} ;
            PageReference p = new PageReference(baseUrl+'/apex/InvoicePDFController?id=' + this.record.Id);
            // PageReference p = new PageReference('/apex/HelloVFP');
            // PageReference p = new PageReference('https://novascotiacollegeofpharmacists.lightning.force.com/apex/InvoicePDFController?id=a0WJQ000000wFBZ2A2');
            p.setRedirect(true);
            return p; 
        } catch (Exception err) {
            System.debug('Error: ' + err.getMessage());
            return null;
        }
    }
    
    
}